import type { Sku } from '$lib/sku-item/types';
import lanfingTile from '$project/landing/images/landing-tile.png';
import firstTile from '$project/landing/images/first-tile.png';
import secondTile from '$project/landing/images/second-tile.png';
import thirdTile from '$project/landing/images/third-tile.png';
import fourthTile from '$project/landing/images/fourth-tile.png';

export const skuLandingHeadData = (): Sku => {
  return {
    _id: 'EmiliaClarke',
    redeemable: true,
    name: 'Terrarium',
    issuer: {
      _id: '1',
      createdAt: new Date('2021-12-12'),
      externalId: '',
      hederaAccount: '',
      role: '',
      updatedAt: new Date('2021-12-12'),
      username: 'Emilia Clarke',
      profilePhotoUrl: '',
      bannerPhotoUrl: '',
      midPhotoUrl: '',
      descriptionIcon: '',
      descriptionHeader: '',
      descriptionBody: '',
      footerPhotoUrl: '',
      tagline: '',
    },
    minStartDate: new Date('2020-12-12'),
    maxSupply: 1,
    minPrice: 2000,
    totalSupplyLeft: 10,
    initialBuyersFeePercentage: 5,
    activeSkuListings: [],
    productListings: [],
    nftPublicAssets: [
      {
        bucket: '',
        hash: '',
        height: 20,
        key: '',
        size: 20,
        type: 'image',
        url: lanfingTile,
        width: 20,
      },
    ],
    rarity: 'uncommon',
    description: 'string',
    display: false,
    supplyType: 'variable',
    featured: true,
    imageUrls: [],
    graphicUrl: 'string', // Default image
    issuerName: 'string',
    maxBid: 20,
    minCurrentBid: 10,
    circulatingSupply: 10,
    totalSupply: 10,
    totalSkuSupplyLeft: 10,
    totalUpcomingSupply: 10,
    totalSkuListingSupplyLeft: 10,
    countSkuListings: 10,
    countAllSkuListings: 10,
    series: {
      _id: 'string',
      name: 'string',
      description: 'string',
      issuerId: 'string',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    category: {
      _id: 'string',
      name: 'string',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    royaltyFeePercentage: 1,
    resaleSellersFeePercentage: 1,
    sellerTransactionFeePercentage: 1,
    skuListings: [],
    sellerTransactionFeePercentageSecondary: 1,
    type: 'str',
    upcomingProductListings: [],
    upcomingSkuListings: [],
    activeProductListings: [],
  };
};

// const listing: Listing = {
//   canceled: false,
//   price: 10,
//   product: 'string',
//   saleType: 'auction',
//   startDate: new Date(),
//   status: 'active',
//   supply: 10,
//   supplyLeft: 10,
//   type: 'string',
//   _id: 'string',
//   endDate: new Date(),
//   minBid: 10,
//   issuer: {},
//   createdAt: new Date(),
//   updatedAt: new Date(),
//   auctionBidIncrement: 10,
// };

export const skuGridLandingData = (): Sku[] => {
  return [
    {
      _id: '2',
      redeemable: false,
      name: 'Capsules',
      issuer: {
        _id: '2',
        createdAt: new Date('2021-12-12'),
        externalId: '',
        hederaAccount: '',
        role: '',
        updatedAt: new Date('2021-12-12'),
        username: 'Emilia Clarke',
        profilePhotoUrl: '',
        bannerPhotoUrl: '',
        midPhotoUrl: '',
        descriptionIcon: '',
        descriptionHeader: '',
        descriptionBody: '',
        footerPhotoUrl: '',
        tagline: '',
      },
      productListings: [],
      skuListings: [],
      minStartDate: new Date('2900-12-12'),
      maxSupply: 1,
      minPrice: 2000,
      nftPublicAssets: [
        {
          bucket: '',
          hash: '',
          height: 20,
          key: '',
          size: 20,
          type: 'image',
          url: firstTile,
          width: 20,
        },
      ],
      rarity: 'uncommon',
      description: 'string',
      display: false,
      supplyType: 'variable',
      featured: true,
      imageUrls: [],
      graphicUrl: 'string', // Default image
      issuerName: 'string',
      maxBid: 20,
      minCurrentBid: 10,
      circulatingSupply: 10,
      totalSupply: 10,
      totalSkuSupplyLeft: 10,
      totalUpcomingSupply: 10,
      totalSkuListingSupplyLeft: 10,
      countSkuListings: 10,
      countAllSkuListings: 10,
      initialBuyersFeePercentage: 5,
      series: {
        _id: 'string',
        name: 'string',
        description: 'string',
        issuerId: 'string',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      category: {
        _id: 'string',
        name: 'string',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      royaltyFeePercentage: 1,
      resaleSellersFeePercentage: 1,
      sellerTransactionFeePercentage: 1,
      sellerTransactionFeePercentageSecondary: 1,
      type: 'str',
      upcomingProductListings: [],
      upcomingSkuListings: [],
      activeProductListings: [],
      totalSupplyLeft: 0,
      activeSkuListings: [],
    },
    {
      _id: '3',
      redeemable: true,
      name: 'Dress',
      issuer: {
        _id: '3',
        createdAt: new Date('2021-12-12'),
        externalId: '',
        hederaAccount: '',
        role: '',
        updatedAt: new Date('2021-12-12'),
        username: 'Emilia Clarke',
        profilePhotoUrl: '',
        bannerPhotoUrl: '',
        midPhotoUrl: '',
        descriptionIcon: '',
        descriptionHeader: '',
        descriptionBody: '',
        footerPhotoUrl: '',
        tagline: '',
      },
      minStartDate: new Date('2020-12-12'),
      maxSupply: 1,
      totalSupplyLeft: 10,
      activeSkuListings: [],
      productListings: [],
      totalUpcomingSupply: 268,
      supplyType: 'fixed',
      minPrice: 14,

      nftPublicAssets: [
        {
          bucket: '',
          hash: '',
          height: 20,
          key: '',
          size: 20,
          type: 'image',
          url: secondTile,
          width: 20,
        },
      ],
      rarity: 'uncommon',
      description: 'string',
      display: false,
      featured: true,
      imageUrls: [],
      graphicUrl: 'string', // Default image
      issuerName: 'string',
      initialBuyersFeePercentage: 5,
      maxBid: 20,
      minCurrentBid: 10,
      circulatingSupply: 10,
      totalSupply: 10,
      totalSkuSupplyLeft: 10,
      totalSkuListingSupplyLeft: 10,
      countSkuListings: 10,
      countAllSkuListings: 10,
      series: {
        _id: 'string',
        name: 'string',
        description: 'string',
        issuerId: 'string',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      category: {
        _id: 'string',
        name: 'string',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      royaltyFeePercentage: 1,
      resaleSellersFeePercentage: 1,
      sellerTransactionFeePercentage: 1,
      skuListings: [],
      sellerTransactionFeePercentageSecondary: 1,
      type: 'str',
      upcomingProductListings: [],
      upcomingSkuListings: [],
      activeProductListings: [],
    },
    {
      _id: '4',
      redeemable: true,
      name: 'Gems',
      issuer: {
        _id: '4',
        createdAt: new Date('2021-12-12'),
        externalId: '',
        hederaAccount: '',
        role: '',
        updatedAt: new Date('2021-12-12'),
        username: 'Emilia Clarke',
        profilePhotoUrl: '',
        bannerPhotoUrl: '',
        midPhotoUrl: '',
        descriptionIcon: '',
        descriptionHeader: '',
        descriptionBody: '',
        footerPhotoUrl: '',
        tagline: '',
      },
      totalUpcomingSupply: 268,
      minStartDate: new Date('2020-12-12'),
      maxSupply: 1,
      totalSupplyLeft: 10,
      initialBuyersFeePercentage: 5,

      activeSkuListings: [],
      productListings: [],
      supplyType: 'fixed',
      minPrice: 20,
      nftPublicAssets: [
        {
          bucket: '',
          hash: '',
          height: 20,
          key: '',
          size: 20,
          type: 'image',
          url: thirdTile,
          width: 20,
        },
      ],
      rarity: 'uncommon',
      description: 'string',
      display: false,
      featured: true,
      imageUrls: [],
      graphicUrl: 'string', // Default image
      issuerName: 'string',
      maxBid: 20,
      minCurrentBid: 10,
      circulatingSupply: 10,
      totalSupply: 10,
      totalSkuSupplyLeft: 10,
      totalSkuListingSupplyLeft: 10,
      countSkuListings: 10,
      countAllSkuListings: 10,
      series: {
        _id: 'string',
        name: 'string',
        description: 'string',
        issuerId: 'string',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      category: {
        _id: 'string',
        name: 'string',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      royaltyFeePercentage: 1,
      resaleSellersFeePercentage: 1,
      sellerTransactionFeePercentage: 1,
      skuListings: [],
      sellerTransactionFeePercentageSecondary: 1,
      type: 'str',
      upcomingProductListings: [],
      upcomingSkuListings: [],
      activeProductListings: [],
    },
    {
      _id: '5',
      redeemable: false,
      name: 'Capsules',
      issuer: {
        _id: '5',
        createdAt: new Date('2021-12-12'),
        externalId: '',
        hederaAccount: '',
        role: '',
        updatedAt: new Date('2021-12-12'),
        username: 'Emilia Clarke',
        profilePhotoUrl: '',
        bannerPhotoUrl: '',
        midPhotoUrl: '',
        descriptionIcon: '',
        descriptionHeader: '',
        descriptionBody: '',
        footerPhotoUrl: '',
        tagline: '',
      },
      minStartDate: new Date('2020-12-12'),
      maxSupply: 1,
      minPrice: 2000,
      totalSupplyLeft: 10,
      activeSkuListings: [],
      productListings: [],
      totalUpcomingSupply: 268,
      initialBuyersFeePercentage: 5,

      supplyType: 'fixed',
      nftPublicAssets: [
        {
          bucket: '',
          hash: '',
          height: 20,
          key: '',
          size: 20,
          type: 'image',
          url: fourthTile,
          width: 20,
        },
      ],
      rarity: 'uncommon',
      description: 'string',
      display: false,
      featured: true,
      imageUrls: [],
      graphicUrl: 'string', // Default image
      issuerName: 'string',
      maxBid: 20,
      minCurrentBid: 10,
      circulatingSupply: 10,
      totalSupply: 10,
      totalSkuSupplyLeft: 10,
      totalSkuListingSupplyLeft: 10,
      countSkuListings: 10,
      countAllSkuListings: 10,
      series: {
        _id: 'string',
        name: 'string',
        description: 'string',
        issuerId: 'string',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      category: {
        _id: 'string',
        name: 'string',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      royaltyFeePercentage: 1,
      resaleSellersFeePercentage: 1,
      sellerTransactionFeePercentage: 1,
      skuListings: [],
      sellerTransactionFeePercentageSecondary: 1,
      type: 'str',
      upcomingProductListings: [],
      upcomingSkuListings: [],
      activeProductListings: [],
    },
  ];
};
