[build]
  publish = "build/"
  functions = "functions/"

[build.environment]
  NODE_VERSION = "14.18.0"
  SVELTEKIT_ADAPTER = "netlify"

# This build command will be used on "production" builds in netlify.
# The initial command creates a _redirects file that will be used when building the project.
# The added rule will redirect all requests to /api to the actual backend url.
# This redirect is needed for aws cognito to work
[context.production]
  command = 'echo "/api/* $API_URL/:splat  200" > _redirects && npm run build $PROJECT'

# This build command will be used on preview builds in netlify
# Sed is being used to find "VITE_API_URL=" in the .env file and replacing that with the preview url
# This is needed because a url is generated for each preview
[context.deploy-preview]
  command = 'sed -i "s%^.*VITE_API_URL.*$%VITE_API_URL=\"${DEPLOY_PRIME_URL}/api\"%" ./projects/$PROJECT/.env.production && echo "/api/* $API_URL/:splat  200" > _redirects && npm run build $PROJECT'
