[build]
  publish = "build/"
  functions = "functions/"

[build.environment]
  NODE_VERSION = "14.18.0"
  SVELTEKIT_ADAPTER = "netlify"

[context.deploy-preview]
  command = 'sed -i "s%^.*VITE_API_URL.*$%VITE_API_URL=\"${DEPLOY_PRIME_URL}/api\"%" ./projects/$PROJECT/.env.production && npm run build $PROJECT'
