export const paths = {
  '$project/about/*': 'projects/aria/src/about/*',
  '$project/collection/*': 'projects/aria/src/collection/*',
  '$ui/pagination/assets/chevron-left': 'projects/infinite/src/assets/lib/arrow-left',
  '$lib/features/wallet/assets/arrow-right': 'projects/mclaren/src/assets/lib/arrow-right',
  '$lib/features/wallet/assets/info': 'projects/mclaren/src/assets/lib/info',
  '$lib/features/sku/assets/arrow-right': 'projects/infinite/src/assets/lib/arrow-right',
  '$lib/features/sku/assets/share': 'projects/infinite/src/assets/lib/share',
  '$lib/components/icons/magnify': 'projects/infinite/src/assets/lib/magnify',
  '$lib/features/account/Account.svelte': 'projects/mclaren/src/account/Account.svelte',
  '$lib/features/account/assets/PencilIcon.svelte': 'projects/mclaren/src/assets/lib/PencilIcon.svelte',
  '$lib/features/product/assets/arrow-right': 'projects/mclaren/src/assets/lib/arrow-right',
  '$lib/features/wallet/kyc/assets/ArrowRight.svelte': 'projects/mclaren/src/assets/lib/arrow-right.svelte',
  '$lib/components/icons/arrow-down': 'projects/mclaren/src/assets/lib/arrow-down',
  '$lib/components/icons/arrow-up': 'projects/mclaren/src/assets/lib/arrow-up',
  '$lib/features/wallet/assets/chevron-right': 'projects/mclaren/src/assets/lib/chevron-right',
  '$ui/modals/assets/close': 'projects/mclaren/src/assets/lib/close-icon',
};
