name: 'Node and pnpm'
description: 'Setup a NodeJS environment and install pnpm'

inputs:
  node-version:
    description: 'Node version to use'
    required: true

runs:
  using: 'composite' # Mandatory parameter
  steps:
    # Setup a Node environment given a node version
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install PNPM
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6
        run_install: true
