name: CI

on:
  push:
    branches:
      - 'main'
  pull_request: {}

env:
  node-version: 16.x

jobs:
  lint_test_build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ./.github/actions/node-pnpm
        with:
          node-version: ${{ env.node-version }}

      - name: Check commit message
        run: pnpx commitlint --config commitlint.config.cjs --from HEAD~1

      - name: Check format
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: Setup project
        run: pnpm use aria

      - name: Check Svelte
        run: pnpm check

      - name: Test
        run: pnpm test

  e2e:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        run: ['aria', 'infinite', 'seva', 'mclaren']

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ./.github/actions/node-pnpm
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        run: pnpx playwright install

      - name: Run
        run: |
          pnpm build ${{ matrix.run }}
          pnpm preview &
        env:
          VITE_API_URL: https://api-dev.infiniteworld.com
          SVELTEKIT_MODE: development

      - name: E2E
        run: pnpm e2e ${{ matrix.run }}

      # - name: E2E Artifacts
      #   uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: cypress-videos
      #     path: cypress/videos
      #     retention-days: 30
