name: CI

on:
  push:
    branches:
      - 'main'
  pull_request: {}

env:
  node-version: 14.x

jobs:
  lint_test_build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ./.github/actions/node-pnpm
        with:
          node-version: ${{ env.node-version }}

      - name: Check commit message
        run: pnpx commitlint --config commitlint.config.cjs --from HEAD~1

      - name: Check format
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: Setup project
        run: pnpm use aria

      - name: Check Svelte
        run: pnpm check

      - name: Test
        run: pnpm test

  cypress_test:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        run: ['aria', 'infinite', 'seva', 'mclaren']

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ./.github/actions/node-pnpm
        with:
          node-version: ${{ env.node-version }}

      - name: Build
        run: pnpm build ${{ matrix.run }}
        env:
          VITE_API_URL: https://api-dev.infiniteworld.com
          SVELTEKIT_MODE: development

      - name: E2E
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          install: false
          start: pnpm preview
          config-file: projects/${{ matrix.run }}/cypress.config.json

      - name: E2E Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 30
