name: CI

on:
  push:
    branches:
      - 'main'
  pull_request: {}

env:
  node-version: 14.x

jobs:
  lint_test_build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: true

      - name: Check commit message
        run: pnpx commitlint --from HEAD~1

      - name: Check format
        run: pnpm format:check

      - name: Check Svelte
        run: pnpm check

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
